version: '3'

services:
  frontend:
      build: ./frontend
      ports:
        - "3000:3000"
  broker_service:  # The name of your service
    build: ./backend/broker_service  # Specifies the Dockerfile location. Here, it's in the same directory
    container_name: broker_service
    ports:
      - "8000:8000"  # Forward the exposed port 5000 on the container to port 5000 on the host machine
    # env_file:
    #   - ".env"
    networks:
      - immigration_in_Ireland
  data_service: 
    build: ./backend/data_service  
    container_name: data_service 
    ports:
      - "8001:8001" 
    # env_file:
    #   - ".env"
    networks:
      - immigration_in_Ireland
  preprocess_service: 
    build: ./backend/preprocessing_pipeline
    container_name: preprocess_service  
    ports:
      - "8002:8002" 
    # env_file:
    #   - ".env"
    networks:
      - immigration_in_Ireland
  nlp_service: 
    build: ./backend/nlp_engine
    container_name: nlp_service   
    ports:
      - "8003:8003"
    # env_file:
    #   - ".env"
    networks:
      - immigration_in_Ireland

networks:
  immigration_in_Ireland: