name: Push Container to Heroku

on:
    push:
      branches:
      - main
      - ft_vincent

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: bf110185-687e-4945-8d6d-899d4b5c822f
      run: heroku container:login 
    - name: Build and push
      env:
        HEROKU_API_KEY: bf110185-687e-4945-8d6d-899d4b5c822f
      run: heroku container:push -a frontend web 
    - name: Release
      env:
        HEROKU_API_KEY: bf110185-687e-4945-8d6d-899d4b5c822f
      run: heroku container:release -a frontend web 
 