name: Push Container to Heroku

on:
    push:
      branches:
      - main
      - ft_vincent

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        file_name: .env
    - name: Display Environment Variables
      run: |
        echo "HEROKU_API_KEY: ${HEROKU_API_KEY}"
    - uses: actions/checkout@v2
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: $HEROKU_API_KEY
      run: heroku container:login 
    - name: Build and push
      env:
        HEROKU_API_KEY: $HEROKU_API_KEY
      run: heroku container:push -a frontend web 
    - name: Release
      env:
        HEROKU_API_KEY: $HEROKU_API_KEY
      run: heroku container:release -a frontend web 
 