name: Run Tests on Merge

on:
  push:
    branches:
    - main
    - ft_vincent
  pull_request:
    branches:
    - main 
    - ft_vincent

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: load env vars
        env:
          # backend
          MYSQL_HOST: db-dev.coeqkin68k7t.eu-west-1.rds.amazonaws.com
          MYSQL_DB: alpha
          MYSQL_ROOT_USERNAME: dev
          MYSQL_ROOT_PASSWORD: dev12345
          MONGO_URI: mongodb+srv://admin:admin@cluster0.ado3i.mongodb.net/team-project?retryWrites=true&w=majority
          CLIENT_SECRET: AIzaSyB4BUYCNk9bLiKgrYUZtOeM30sZKyRzBWE
          CLIENT_SECRET1: AIzaSyB6uH0JbMQsbudW2Lg1UT1JXSEH5TGSCIk
          CLIENT_SECRET2: AIzaSyAaYVoxZ-xpSn3Rzl1gNpg1cplPhOyEaZY
          CLIENT_SECRET3: AIzaSyAL73Mg10dElfe0G_P1MFVsctLhY4e6qb8 
          BOOTSTRAP_SERVERS: pkc-z9doz.eu-west-1.aws.confluent.cloud:9092
          SECURITY_PROTOCOL: SASL_SSL
          SASL_MECHANISMS: PLAIN
          SASL_USERNAME: PR6L4XJHNR3TI33I
          SASL_PASSWORD: xs38vTm+VwsTO9/VZwmHh4DQgyORiVx5K7LlkGDqLy02llk4mrWpvqdRF5+BZOJc
          SESSION_TIMEOUT_MS: 45000
          # frontend
          REACT_APP_YOUTUBE_API_KEY: AIzaSyB4BUYCNk9bLiKgrYUZtOeM30sZKyRzBW
          REACT_APP_NLP_PLATFORM_API_URL: http://127.0.0.1:8000 # prod server url should use here
        run: echo $VARIABLE_NAME
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.ci.yml build








